import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
// import "././cesium/Widgets/widgets.css";
import "../../public/cesium/Widgets/widgets.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="cesium/Widgets/widgets.css" />
      </Head>
      <body className={inter.className}>{children}</body>
      {/* <body className="flex place-items-center min-h-[100svh] touch-none m-0 p-2 justify-center">{children}</body> */}
    </html>
  );
}
